-- 코드를 입력하세요
SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    30 * (100 - DISCOUNT_RATE) / 100 * DAILY_FEE AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON C.CAR_TYPE = DP.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE 30 * (100 - DISCOUNT_RATE) / 100 * DAILY_FEE >= 500000
    AND 30 * (100 - DISCOUNT_RATE) / 100 * DAILY_FEE < 2000000
    # 조회일자 <- 중요한 부분
    AND NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
        WHERE RH.CAR_ID = C.CAR_ID
            AND RH.START_DATE <= '2022-11-30'
            AND RH.END_DATE >= '2022-11-01'
    )
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC