-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, REST_ID, REST_NAME, RI.FAVORITES
FROM REST_INFO AS RI
    JOIN (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) AS MF
    ON RI.FOOD_TYPE = MF.FOOD_TYPE AND RI.FAVORITES = MF.FAVORITES
ORDER BY RI.FOOD_TYPE DESC