-- 코드를 입력하세요
SELECT HISTORY_ID, DAILY_FEE * RENTAL_DATE * (100 - IFNULL(DISCOUNT_RATE, 0)) * 0.01 AS FEE
FROM (
        SELECT
            HISTORY_ID,
            C.CAR_ID,
            C.CAR_TYPE,
            DAILY_FEE,
            DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DATE,
            CASE
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
                ELSE NULL
            END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_CAR AS C
            JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
            ON C.CAR_ID = RH.CAR_ID
        WHERE CAR_TYPE = '트럭'
    ) AS CAR
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON CAR.CAR_TYPE = DP.CAR_TYPE AND CAR.DURATION_TYPE = DP.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC