-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, MAX(DISTINCT(FI.LENGTH)) AS LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI
    ON FI.FISH_TYPE = FNI.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS M
    ON FI.FISH_TYPE = M.FISH_TYPE
    AND FI.LENGTH = M.MAX_LENGTH
GROUP BY FNI.FISH_TYPE
ORDER BY FI.ID