-- 코드를 입력하세요
SELECT TITLE, UGB.BOARD_ID, REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, UGR.CREATED_DATE
FROM USED_GOODS_BOARD AS UGB
    JOIN USED_GOODS_REPLY AS UGR
    ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE
    '2022-10-01' <= UGB.CREATED_DATE AND UGB.CREATED_DATE < '2022-11-01'
ORDER BY
    UGR.CREATED_DATE,
    TITLE