-- 코드를 입력하세요
SELECT FP.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
    JOIN (
        SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
        GROUP BY CATEGORY
    ) AS MP
    ON FP.CATEGORY = MP.CATEGORY AND FP.PRICE = MP.MAX_PRICE
ORDER BY MAX_PRICE DESC